### ISSUE TITLE
KeyError: "Unable to open object (object 'chroms' doesn't exist)"

### ISSUE THREAD

**Issue by YiweiNiu** [dejunlin/hicrep#12]
Hi,

Thank you for this cool tool.

I installed hicrep through pip, and got the following error when I used it.

```bash
$ hicrep M0_1.mcool M0_2.mcool outputSCC.txt --h 1 --dBPMax 10000000
Traceback (most recent call last):
  File "/home/niuyw/software/anaconda3.7/envs/hicrep/lib/python3.9/site-packages/cooler/api.py", line 95, in _refresh
    _ct = chroms(grp)
  File "/home/niuyw/software/anaconda3.7/envs/hicrep/lib/python3.9/site-packages/cooler/api.py", line 448, in chroms
    .append(pd.Index(h5["chroms"].keys()))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/niuyw/software/anaconda3.7/envs/hicrep/lib/python3.9/site-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'chroms' doesn't exist)"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/niuyw/software/anaconda3.7/envs/hicrep/bin/hicrep", line 8, in <module>
    sys.exit(main())
  File "/home/niuyw/software/anaconda3.7/envs/hicrep/lib/python3.9/site-packages/hicrep/__init__.py", line 80, in main
    cool1, binSize1 = readMcool(fmcool1, binSize)
  File "/home/niuyw/software/anaconda3.7/envs/hicrep/lib/python3.9/site-packages/hicrep/utils.py", line 34, in readMcool
    cool = cooler.Cooler(mcool)
  File "/home/niuyw/software/anaconda3.7/envs/hicrep/lib/python3.9/site-packages/cooler/api.py", line 89, in __init__
    self._refresh()
  File "/home/niuyw/software/anaconda3.7/envs/hicrep/lib/python3.9/site-packages/cooler/api.py", line 104, in _refresh
    listing = list_coolers(self.store)
  File "/home/niuyw/software/anaconda3.7/envs/hicrep/lib/python3.9/site-packages/cooler/fileops.py", line 188, in list_coolers
    if not h5py.is_hdf5(filepath):
  File "/home/niuyw/software/anaconda3.7/envs/hicrep/lib/python3.9/site-packages/h5py/_hl/base.py", line 34, in is_hdf5
    fname = os.path.abspath(fspath(fname))
TypeError: expected str, bytes or os.PathLike object, not File
```

The `mcool` file looks like this.

```bash
$ cooler attrs M0_1.mcool 
'@attrs':
  format: HDF5::MCOOL
  format-version: 2
resolutions:
  '1000000':
    '@attrs':
      bin-size: 1000000
      bin-type: fixed
      creation-date: 2021-05-18 16:43:44.013710
      format: HDF5::Cooler
      format-url: https://github.com/open2c/cooler
      format-version: 3
      generated-by: cooler-0.8.11
      genome-assembly: unknown
      metadata: {}
      nbins: 2738
      nchroms: 22
      nnz: 1591928
      storage-mode: symmetric-upper
      sum: 6885169
    bins:
      '@attrs': {}
      chrom:
        '@attrs': {}
      end:
        '@attrs': {}
      start:
        '@attrs': {}
      weight:
        '@attrs':
          cis_only: false
          converged: true
          ignore_diags: 2
          mad_max: 5
          min_count: 0
          min_nnz: 10
          scale: 3417.6785530450925
          tol: 1.0e-05
          var: 6.7006041416248e-06
    chroms:
      '@attrs': {}
      length:
        '@attrs': {}
      name:
        '@attrs': {}
    indexes:
      '@attrs': {}
      bin1_offset:
        '@attrs': {}
      chrom_offset:
        '@attrs': {}
    pixels:
      '@attrs': {}
      bin1_id:
        '@attrs': {}
      bin2_id:
        '@attrs': {}
      count:
        '@attrs': {}
  '2000000':
    '@attrs':
      bin-size: 2000000
      bin-type: fixed
      creation-date: 2021-05-18 16:43:47.734047
      format: HDF5::Cooler
      format-url: https://github.com/open2c/cooler
      format-version: 3
      generated-by: cooler-0.8.11
      genome-assembly: unknown
      metadata: {}
      nbins: 1376
      nchroms: 22
      nnz: 739487
      storage-mode: symmetric-upper
      sum: 6885169
    bins:
      '@attrs': {}
      chrom:
        '@attrs': {}
      end:
        '@attrs': {}
      start:
        '@attrs': {}
      weight:
        '@attrs':
          cis_only: false
          converged: true
          ignore_diags: 2
          mad_max: 5
          min_count: 0
          min_nnz: 10
          scale: 6346.484655522293
          tol: 1.0e-05
          var: 4.2289736578993755e-06
    chroms:
      '@attrs': {}
      length:
        '@attrs': {}
      name:
        '@attrs': {}
    indexes:
      '@attrs': {}
      bin1_offset:
        '@attrs': {}
      chrom_offset:
        '@attrs': {}
    pixels:
      '@attrs': {}
      bin1_id:
        '@attrs': {}
      bin2_id:
        '@attrs': {}
      count:
        '@attrs': {}
  '4000000':
    '@attrs':
      bin-size: 4000000
      bin-type: fixed
      creation-date: 2021-05-18 16:43:48.440148
      format: HDF5::Cooler
      format-url: https://github.com/open2c/cooler
      format-version: 3
      generated-by: cooler-0.8.11
      genome-assembly: unknown
      metadata: {}
      nbins: 694
      nchroms: 22
      nnz: 220042
      storage-mode: symmetric-upper
      sum: 6885169
    bins:
      '@attrs': {}
      chrom:
        '@attrs': {}
      end:
        '@attrs': {}
      start:
        '@attrs': {}
      weight:
        '@attrs':
          cis_only: false
          converged: true
          ignore_diags: 2
          mad_max: 5
          min_count: 0
          min_nnz: 10
          scale: 11690.429853353084
          tol: 1.0e-05
          var: 6.810218703424982e-06
    chroms:
      '@attrs': {}
      length:
        '@attrs': {}
      name:
        '@attrs': {}
    indexes:
      '@attrs': {}
      bin1_offset:
        '@attrs': {}
      chrom_offset:
        '@attrs': {}
    pixels:
      '@attrs': {}
      bin1_id:
        '@attrs': {}
      bin2_id:
        '@attrs': {}
      count:
        '@attrs': {}
  '8000000':
    '@attrs':
      bin-size: 8000000
      bin-type: fixed
      creation-date: 2021-05-18 16:43:48.758667
      format: HDF5::Cooler
      format-url: https://github.com/open2c/cooler
      format-version: 3
      generated-by: cooler-0.8.11
      genome-assembly: unknown
      metadata: {}
      nbins: 354
      nchroms: 22
      nnz: 57568
      storage-mode: symmetric-upper
      sum: 6885169
    bins:
      '@attrs': {}
      chrom:
        '@attrs': {}
      end:
        '@attrs': {}
      start:
        '@attrs': {}
      weight:
        '@attrs':
          cis_only: false
          converged: true
          ignore_diags: 2
          mad_max: 5
          min_count: 0
          min_nnz: 10
          scale: 20811.188587116743
          tol: 1.0e-05
          var: 3.814639544957634e-06
    chroms:
      '@attrs': {}
      length:
        '@attrs': {}
      name:
        '@attrs': {}
    indexes:
      '@attrs': {}
      bin1_offset:
        '@attrs': {}
      chrom_offset:
        '@attrs': {}
    pixels:
      '@attrs': {}
      bin1_id:
        '@attrs': {}
      bin2_id:
        '@attrs': {}
      count:
        '@attrs': {}
  '@attrs': {}
```

Do you have any ideas about this?

Thank you in advance.

**Comment by justin-a-sanders** [comment]
When working with a .mcool file with multiple resolutions, please specify the --binsize parameter. This indicates what resolution to compute the similarity at. An example is in the README has an example. 
Hope that helps!

**Comment by YiweiNiu** [comment]
Got it. Thank you for your reply!
